### PR TITLE
check if entity before call the dirty function

### PR DESCRIPTION
**Pull request by eymen-elkum**
This is necessary when we set hydrate to false 

```
        $apps = $this->Apps->find()->where([
            'user_id' => $user['user']['id']
        ])->hydrate(false)->first();
```

### CODE REVIEW

**Comment by dereuromark** [comment]
Can we also have a test for this please?

**Comment by eymen-elkum** [comment]
I used this lines, and the [$row](https://github.com/dereuromark/cakephp-hashid/blob/master/src/Model/Behavior/HashidBehavior.php#L234) then is array and not entity

```
        $apps = $this->Apps->find()->where([
            'user_id' => $user['user']['id']
        ])->hydrate(false)->first();
```

**Comment by eymen-elkum** [comment]
Fatal error: Call to a member function dirty() on a non-object in \vendor\dereuromark\cakephp-hashid\src\Model\Behavior\HashidBehavior.php on line 234

**Comment by dereuromark** [comment]
Please fix CS as well. So tests are green again.

**Pull request merged**
